# Generated by Django 3.1.1 on 2022-01-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20220104_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('TLE', 'TLE'), ('WA', 'WA'), ('AC', 'AC'), ('procesing', 'processing'), ('queue', 'queue'), ('NA', 'NA')], default='queue', max_length=20),
        ),
    ]
