# Generated by Django 3.1.1 on 2022-01-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20220104_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontest',
            name='output_file',
            field=models.FilePathField(null=True, path='submission_test', unique=True),
        ),
    ]
