# Generated by Django 3.1.1 on 2022-01-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20220106_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('TLE', 'TLE'), ('WA', 'WA'), ('AC', 'AC'), ('processing', 'processing'), ('queue', 'queue'), ('NA', 'NA')], default='queue', max_length=20),
        ),
    ]
