# Generated by Django 3.1.1 on 2022-01-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20220108_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontest',
            old_name='output_file',
            new_name='output',
        ),
    ]
