# Generated by Django 3.1.1 on 2021-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20211224_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='test case', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='test case', max_length=250),
            preserve_default=False,
        ),
    ]
