# Generated by Django 3.1.1 on 2021-12-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20211226_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='input_file',
            field=models.FilePathField(match='input_file*', path='test_case', unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='output_file',
            field=models.FilePathField(match='output_file*', path='test_case', unique=True),
        ),
    ]
