# Generated by Django 3.1.1 on 2022-01-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20211226_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='statement',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_count',
        ),
        migrations.RemoveField(
            model_name='test',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='output_file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.TextField(default=[1, 2]),
            preserve_default=False,
        ),
    ]
