# Generated by Django 3.1.1 on 2022-01-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20220108_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answer',
            field=models.TextField(default=[1]),
            preserve_default=False,
        ),
    ]
